/**
 * Hero data for LastWar game
 * Based on Last War Handbook database with real skills and stats
 * Each hero has 4 abilities: Normal, Passive, Special, Ultimate
 */

export type HeroRarity = 'UR' | 'SSR' | 'SR' | 'R';
export type HeroType = 'Tanque' | 'Míssil' | 'Aeronave';
export type HeroRole = 'Dano' | 'Defesa' | 'Suporte';
export type SquadPosition = 'Front Row' | 'Back Row';
export type AbilityType = 'Damage' | 'Defense' | 'Support' | 'Control';
export type HeroTier = 'S+' | 'S' | 'A+' | 'A' | 'B+' | 'B' | 'D';

export interface Ability {
  id: string;
  name: string;
  description: string;
  type: AbilityType;
  unlocksAt: number;
  maxLevel: number;
}

export interface HeroStats {
  atk: number;
  def: number;
  hp: number;
  spd: number;
}

export interface Hero {
  id: string;
  name: string;
  rarity: HeroRarity;
  type: HeroType;
  role: HeroRole;
  position: SquadPosition;
  tier: 'S+' | 'S' | 'A+' | 'A' | 'B+' | 'B' | 'D';
  image: string;
  description?: string;
  abilities: Ability[];
  stats: HeroStats;
}

const createAbility = (id: string, name: string, desc: string, type: AbilityType, unlocksAt: number = 1): Ability => ({
  id,
  name,
  description: desc,
  type,
  unlocksAt,
  maxLevel: 30,
});

const createStats = (atk: number, def: number, hp: number, spd: number): HeroStats => ({
  atk,
  def,
  hp,
  spd,
});

export const HEROES: Hero[] = [
  // ===== TANQUE (Tipo do herói) =====
  {
    id: 'murphy',
    name: 'Murphy',
    rarity: 'UR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'A',
    image: '/heroes/murphy.png',
    description: 'Free tutorial Tank hero. Excellent survivability and front-row protection.',
    abilities: [
      createAbility('murphy-1', 'Cannon Fire', 'Dispara canhão causando dano físico a inimigos. Dano base aumenta com nível.', 'Damage', 1),
      createAbility('murphy-2', 'Stand Firm', 'Passiva: Aumenta defesa permanentemente em 20%. Efeito acumula com equipamentos.', 'Defense', 1),
      createAbility('murphy-3', 'Iron Skin', 'Reduz dano recebido por 25% por 8 segundos. Pode ser usado repetidamente.', 'Defense', 2),
      createAbility('murphy-4', 'Last Stand', 'Ultimate: Absorve dano para aliados próximos. Aumenta resistência do esquadrão.', 'Support', 3),
    ],
    stats: createStats(2400, 2800, 26000, 85),
  },
  {
    id: 'marshall',
    name: 'Marshall',
    rarity: 'UR',
    type: 'Tanque',
    role: 'Suporte',
    position: 'Front Row',
    tier: 'S',
    image: '/heroes/marshall.png',
    description: 'S-tier Support Tank. Provides team-wide attack buff and cooldown speed boost.',
    abilities: [
      createAbility('marshall-1', 'Triad Harmony', 'Buff de ataque em equipe +30%. Aumenta dano de todos os aliados simultaneamente.', 'Support', 1),
      createAbility('marshall-2', 'Rapid Start', 'Passiva: Aumenta velocidade de recarga de habilidades em 40%. Essencial para rotações rápidas.', 'Support', 1),
      createAbility('marshall-3', 'Coordinated Strike', 'Aumenta dano crítico de aliados por 15%. Melhora efetividade de ataques.', 'Support', 2),
      createAbility('marshall-4', 'Perfect Synergy', 'Ultimate: Sincroniza ataques do esquadrão para dano massivo combinado.', 'Support', 3),
    ],
    stats: createStats(2800, 3400, 30000, 80),
  },
  {
    id: 'williams',
    name: 'Williams',
    rarity: 'UR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'S',
    image: '/heroes/williams.png',
    description: 'S-tier defensive Tank. Provides massive damage reduction to frontline allies.',
    abilities: [
      createAbility('williams-1', 'Stun Bomb', 'Dispara bomba explosiva causando dano e atordoamento. Imobiliza inimigos por 3 segundos.', 'Control', 1),
      createAbility('williams-2', 'All-Around Armor', 'Passiva: Reduz todo dano recebido em 30%. Efeito mais forte contra dano físico.', 'Defense', 1),
      createAbility('williams-3', 'Iron Will', 'Aumenta defesa da frente em 50%. Protege aliados na primeira linha.', 'Defense', 2),
      createAbility('williams-4', 'Super Sensing', 'Ultimate: Aumenta HP, ATK e DEF em 20%. Melhora significativa de stats.', 'Support', 3),
    ],
    stats: createStats(3200, 2200, 20000, 95),
  },
  {
    id: 'kimberly',
    name: 'Kimberly',
    rarity: 'UR',
    type: 'Tanque',
    role: 'Dano',
    position: 'Front Row',
    tier: 'S',
    image: '/heroes/kimberly.png',
    description: 'Top-tier Tank hero with devastating AoE energy damage. Essential for tank formations.',
    abilities: [
      createAbility('kimberly-1', 'Energy Assault', 'Ataque de energia AoE devastador causando dano a todos os inimigos. Dano aumenta com ATK.', 'Damage', 1),
      createAbility('kimberly-2', 'Energy Boost', 'Passiva: Aumenta dano de energia do esquadrão em 30%. Beneficia todos os aliados.', 'Support', 1),
      createAbility('kimberly-3', 'Tactical Strike', 'Ataque de energia focado com efeito de atordoamento. Alvo único com dano alto.', 'Control', 2),
      createAbility('kimberly-4', 'Energy Mastery', 'Ultimate: Aumenta dano de energia em 50% e reduz cooldown de habilidades.', 'Support', 3),
    ],
    stats: createStats(2200, 3200, 28000, 85),
  },
  {
    id: 'violet',
    name: 'Violet',
    rarity: 'SSR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'A',
    image: '/heroes/violet.png',
    description: 'Strong tank that can be upgraded to UR. Provides damage reduction against monsters.',
    abilities: [
      createAbility('violet-1', 'Plasma Burst', 'Libera explosão de plasma causando dano em área. Afeta múltiplos inimigos.', 'Damage', 1),
      createAbility('violet-2', 'Energy Shield', 'Passiva: Cria escudo de energia reduzindo dano recebido em 20%.', 'Defense', 1),
      createAbility('violet-3', 'Plasma Control', 'Controla energia de plasma aumentando defesa em 25%.', 'Defense', 2),
      createAbility('violet-4', 'Energy Master', 'Ultimate: Domina energia de plasma aumentando todos os stats em 15%.', 'Support', 3),
    ],
    stats: createStats(2800, 1400, 14000, 92),
  },
  {
    id: 'scarlett',
    name: 'Scarlett',
    rarity: 'SSR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'A',
    image: '/heroes/scarlett.png',
    description: 'SSR Tank that can be upgraded to UR. Provides damage reduction against monsters.',
    abilities: [
      createAbility('scarlett-1', 'Flame Burst', 'Libera explosão de chamas causando dano em área. Queima inimigos continuamente.', 'Damage', 1),
      createAbility('scarlett-2', 'T-5 Armor', 'Passiva: Equipa armadura avançada T-5 aumentando DEF em 25%.', 'Defense', 1),
      createAbility('scarlett-3', 'Flame Defense', 'Defende contra ataques de chama reduzindo dano em 30%.', 'Defense', 2),
      createAbility('scarlett-4', 'Armor Expert', 'Ultimate: Conhecimento expert em armadura aumentando defesa em 40%.', 'Defense', 3),
    ],
    stats: createStats(1600, 1800, 16000, 90),
  },
  {
    id: 'richard',
    name: 'Richard',
    rarity: 'SSR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'A',
    image: '/heroes/richard.png',
    description: 'Strong tank with precision abilities.',
    abilities: [
      createAbility('richard-1', 'Precision Shot', 'Disparo preciso causando dano alto a alvo único. Aumenta com crítico.', 'Damage', 1),
      createAbility('richard-2', 'Marksman Training', 'Passiva: Melhora precisão de tiro aumentando crítico em 20%.', 'Support', 1),
      createAbility('richard-3', 'Focus Fire', 'Concentra fogo em alvo causando dano massivo. Ignora parte da defesa.', 'Damage', 2),
      createAbility('richard-4', 'Sharpshooter', 'Ultimate: Expertise em tiro de precisão aumentando dano crítico em 50%.', 'Damage', 3),
    ],
    stats: createStats(2600, 2200, 24000, 88),
  },
  {
    id: 'gump',
    name: 'Gump',
    rarity: 'SR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'B',
    image: '/heroes/gump.png',
    description: 'Solid early game tank with evasion abilities.',
    abilities: [
      createAbility('gump-1', 'Agile Strike', 'Ataque rápido e ágil causando dano. Aumenta velocidade.', 'Damage', 1),
      createAbility('gump-2', 'Evasion Training', 'Passiva: Melhora evasão aumentando esquiva em 15%.', 'Defense', 1),
      createAbility('gump-3', 'Quick Reflexes', 'Responde rapidamente a ameaças reduzindo dano em 20%.', 'Defense', 2),
      createAbility('gump-4', 'Agile Fighter', 'Ultimate: Lutador ágil aumentando evasão em 35%.', 'Defense', 3),
    ],
    stats: createStats(1800, 2000, 18000, 95),
  },
  {
    id: 'stefmann',
    name: 'Stefmann',
    rarity: 'UR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'S',
    image: '/heroes/stefmann.png',
    description: 'Top-tier tank with plasma abilities.',
    abilities: [
      createAbility('stefmann-1', 'Plasma Cannon', 'Dispara canhão de plasma causando dano em área. Queima inimigos.', 'Damage', 1),
      createAbility('stefmann-2', 'Plasma Shield', 'Passiva: Cria escudo de plasma reduzindo dano em 25%.', 'Defense', 1),
      createAbility('stefmann-3', 'Energy Surge', 'Surge com poder de energia aumentando ATK em 30%.', 'Support', 2),
      createAbility('stefmann-4', 'Plasma Master', 'Ultimate: Domínio de plasma aumentando dano em 40%.', 'Damage', 3),
    ],
    stats: createStats(2700, 3100, 29000, 82),
  },
  {
    id: 'farhad',
    name: 'Farhad',
    rarity: 'SSR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'A',
    image: '/heroes/farhad.png',
    description: 'Desert warrior with tactical abilities.',
    abilities: [
      createAbility('farhad-1', 'Desert Strike', 'Ataque de guerreiro do deserto com táticas especiais. Dano aumentado em deserto.', 'Damage', 1),
      createAbility('farhad-2', 'Sand Shield', 'Passiva: Cria escudo de areia reduzindo dano em 20%.', 'Defense', 1),
      createAbility('farhad-3', 'Desert Tactics', 'Usa táticas de combate do deserto aumentando DEF em 25%.', 'Defense', 2),
      createAbility('farhad-4', 'Desert Warrior', 'Ultimate: Expertise em combate do deserto aumentando todos os stats em 20%.', 'Support', 3),
    ],
    stats: createStats(2400, 2700, 25000, 80),
  },
  {
    id: 'loki',
    name: 'Loki',
    rarity: 'SR',
    type: 'Tanque',
    role: 'Defesa',
    position: 'Front Row',
    tier: 'B',
    image: '/heroes/loki.png',
    description: 'Trickster tank with deception abilities.',
    abilities: [
      createAbility('loki-1', 'Trickster Strike', 'Ataque enganoso usando táticas de enganador. Confunde inimigos.', 'Control', 1),
      createAbility('loki-2', 'Deception', 'Passiva: Confunde inimigos com engano reduzindo precisão em 20%.', 'Control', 1),
      createAbility('loki-3', 'Illusion', 'Cria ilusões para confundir inimigos reduzindo dano em 25%.', 'Defense', 2),
      createAbility('loki-4', 'Master Trickster', 'Ultimate: Expertise em engano aumentando evasão em 40%.', 'Defense', 3),
    ],
    stats: createStats(2000, 2300, 21000, 92),
  },

  // ===== AERONAVE (Tipo do herói) =====
  {
    id: 'dva',
    name: 'DVA',
    rarity: 'UR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'S',
    image: '/heroes/dva.png',
    description: 'S-tier Aircraft damage dealer with exceptional burst damage. Core of any Aircraft team.',
    abilities: [
      createAbility('dva-1', 'Vortex Missile', 'Lança míssil vórtice criando dano em área e efeito de empurrão. Afeta múltiplos inimigos.', 'Damage', 1),
      createAbility('dva-2', 'Armament Upgrade', 'Passiva: Aumenta dano de míssil do esquadrão em 25%.', 'Support', 1),
      createAbility('dva-3', 'Aerial Superiority', 'Concede vantagem aérea e aumenta evasão em 20%.', 'Defense', 2),
      createAbility('dva-4', 'Precision Targeting', 'Ultimate: Aumenta chance de crítico em 40% e dano crítico em 50%.', 'Damage', 3),
    ],
    stats: createStats(2000, 3500, 32000, 75),
  },
  {
    id: 'carlie',
    name: 'Carlie',
    rarity: 'UR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/carlie.png',
    description: 'A-tier Aircraft Tank. Excellent energy damage reduction for the team.',
    abilities: [
      createAbility('carlie-1', 'Dual-string Rocket', 'Lança foguetes duplos com dano dividido. Afeta dois alvos.', 'Damage', 1),
      createAbility('carlie-2', 'Energy Adaption', 'Passiva: Reduz dano de energia recebido pelo esquadrão em 20%.', 'Defense', 1),
      createAbility('carlie-3', 'Aerial Maneuver', 'Aumenta evasão e mobilidade em 25%.', 'Defense', 2),
      createAbility('carlie-4', 'Sky Guardian', 'Ultimate: Protege esquadrão contra ataques aéreos reduzindo dano em 35%.', 'Support', 3),
    ],
    stats: createStats(3600, 1800, 18000, 120),
  },
  {
    id: 'schuyler',
    name: 'Schuyler',
    rarity: 'UR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/schuyler.png',
    description: 'A-tier tech aircraft with precision strikes and system enhancements.',
    abilities: [
      createAbility('schuyler-1', 'Precision Strike', 'Ataque preciso visando pontos fracos. Ignora parte da defesa.', 'Damage', 1),
      createAbility('schuyler-2', 'Tech Upgrade', 'Passiva: Melhora tecnologia do esquadrão aumentando dano em 15%.', 'Support', 1),
      createAbility('schuyler-3', 'System Enhancement', 'Melhora todos os sistemas do esquadrão aumentando stats em 10%.', 'Support', 2),
      createAbility('schuyler-4', 'Tech Mastery', 'Ultimate: Expertise em tecnologia aumentando precisão e dano crítico em 30%.', 'Damage', 3),
    ],
    stats: createStats(3400, 2000, 19000, 115),
  },
  {
    id: 'lucius',
    name: 'Lucius',
    rarity: 'UR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/lucius.png',
    description: 'Elite aircraft pilot with superior aerial combat skills and team coordination.',
    abilities: [
      createAbility('lucius-1', 'Dive Bomb', 'Realiza ataque de mergulho devastador. Dano aumentado contra alvos únicos.', 'Damage', 1),
      createAbility('lucius-2', 'Sky Patrol', 'Passiva: Monitora e protege espaço aéreo reduzindo dano em 15%.', 'Defense', 1),
      createAbility('lucius-3', 'Aerial Combat', 'Aumenta efetividade de combate aéreo em 25%.', 'Damage', 2),
      createAbility('lucius-4', 'Elite Pilot', 'Ultimate: Skills superiores de combate aéreo aumentando dano em 35%.', 'Damage', 3),
    ],
    stats: createStats(3500, 1900, 18000, 125),
  },
  {
    id: 'morrison',
    name: 'Morrison',
    rarity: 'UR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/morrison.png',
    description: 'Naval aviation specialist with versatile combat capabilities.',
    abilities: [
      createAbility('morrison-1', 'Naval Strike', 'Realiza ataque de aviação naval. Dano aumentado contra estruturas.', 'Damage', 1),
      createAbility('morrison-2', 'Carrier Landing', 'Passiva: Otimiza operações de porta-aviões aumentando suporte em 20%.', 'Support', 1),
      createAbility('morrison-3', 'Naval Coordination', 'Coordena com unidades navais aumentando dano em 20%.', 'Support', 2),
      createAbility('morrison-4', 'Naval Specialist', 'Ultimate: Expertise em combate naval aumentando dano em 30%.', 'Damage', 3),
    ],
    stats: createStats(3300, 2100, 19000, 110),
  },
  {
    id: 'sara',
    name: 'Sara',
    rarity: 'SSR',
    type: 'Aeronave',
    role: 'Suporte',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/sara.png',
    description: 'Support aircraft specializing in team coordination.',
    abilities: [
      createAbility('sara-1', 'Support Strike', 'Ataque de suporte enquanto ataca. Beneficia aliados próximos.', 'Support', 1),
      createAbility('sara-2', 'Team Coordination', 'Passiva: Coordena ações do time aumentando efetividade em 20%.', 'Support', 1),
      createAbility('sara-3', 'Support Buff', 'Buffa todo o time aumentando stats em 15%.', 'Support', 2),
      createAbility('sara-4', 'Support Master', 'Ultimate: Expertise em suporte aumentando todos os buffs em 30%.', 'Support', 3),
    ],
    stats: createStats(2600, 2200, 20000, 105),
  },
  {
    id: 'maxell',
    name: 'Maxell',
    rarity: 'SSR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/maxell.png',
    description: 'Energy-based aircraft with powerful damage output.',
    abilities: [
      createAbility('maxell-1', 'Energy Blast', 'Explode com energia pura causando dano massivo. Afeta área.', 'Damage', 1),
      createAbility('maxell-2', 'Energy Control', 'Passiva: Controla energia efetivamente aumentando dano em 20%.', 'Support', 1),
      createAbility('maxell-3', 'Power Surge', 'Surge com poder aumentando ATK em 25%.', 'Support', 2),
      createAbility('maxell-4', 'Energy Master', 'Ultimate: Domínio de energia aumentando dano em 40%.', 'Damage', 3),
    ],
    stats: createStats(3100, 1800, 17000, 100),
  },
  {
    id: 'ambolt',
    name: 'Ambolt',
    rarity: 'SR',
    type: 'Aeronave',
    role: 'Dano',
    position: 'Back Row',
    tier: 'B',
    image: '/heroes/ambolt.png',
    description: 'Lightning-based aircraft with electrical damage.',
    abilities: [
      createAbility('ambolt-1', 'Bolt Strike', 'Ataque com raio causando dano elétrico. Paralisa inimigos.', 'Damage', 1),
      createAbility('ambolt-2', 'Electrical Field', 'Passiva: Cria campo elétrico reduzindo velocidade de inimigos em 15%.', 'Control', 1),
      createAbility('ambolt-3', 'Shock Damage', 'Causa dano de choque continuamente em inimigos.', 'Damage', 2),
      createAbility('ambolt-4', 'Bolt Master', 'Ultimate: Domínio de raios aumentando dano elétrico em 40%.', 'Damage', 3),
    ],
    stats: createStats(2900, 1600, 15000, 110),
  },

  // ===== MÍSSIL (Tipo do herói) =====
  {
    id: 'tesla',
    name: 'Tesla',
    rarity: 'UR',
    type: 'Míssil',
    role: 'Dano',
    position: 'Back Row',
    tier: 'S',
    image: '/heroes/tesla.png',
    description: 'Top DPS Missile Vehicle hero. Incredible energy damage with Inductive Current stacking.',
    abilities: [
      createAbility('tesla-1', 'Lightning Chain', 'Corrente de relâmpagos entre inimigos causando dano contínuo. Afeta múltiplos.', 'Damage', 1),
      createAbility('tesla-2', 'Electric Power Boost', 'Passiva: Aumenta dano elétrico do esquadrão em 35%.', 'Support', 1),
      createAbility('tesla-3', 'Inductive Current', 'Acumula corrente indutiva com cada acerto aumentando dano em 20%.', 'Support', 2),
      createAbility('tesla-4', 'Overcharge', 'Ultimate: Aumenta velocidade de ataque em 60% e dano em 50%.', 'Damage', 3),
    ],
    stats: createStats(3800, 1600, 16000, 110),
  },
  {
    id: 'mcgragor',
    name: 'McGragor',
    rarity: 'UR',
    type: 'Míssil',
    role: 'Defesa',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/mcgragor.png',
    description: 'Highland tank warrior with strong defensive capabilities and team leadership.',
    abilities: [
      createAbility('mcgragor-1', 'Highland Charge', 'Carga com força de guerreiro highland. Dano aumentado contra múltiplos.', 'Damage', 1),
      createAbility('mcgragor-2', 'Defensive Stand', 'Passiva: Toma postura defensiva reduzindo dano em 25%.', 'Defense', 1),
      createAbility('mcgragor-3', 'Highland Tactics', 'Usa táticas de batalha highland aumentando DEF em 30%.', 'Defense', 2),
      createAbility('mcgragor-4', 'Highland Warrior', 'Ultimate: Força de guerreiro highland aumentando dano e defesa em 30%.', 'Support', 3),
    ],
    stats: createStats(2600, 3000, 28000, 75),
  },
  {
    id: 'adam',
    name: 'Adam',
    rarity: 'UR',
    type: 'Míssil',
    role: 'Defesa',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/adam.png',
    description: 'Survivor missile specialist with improvised weapons and adaptability.',
    abilities: [
      createAbility('adam-1', 'Rocket Launcher', 'Lança foguetes poderosos causando dano alto. Dano aumentado com ATK.', 'Damage', 1),
      createAbility('adam-2', 'Makeshift Armor', 'Passiva: Cria armadura improvisada reduzindo dano em 20%.', 'Defense', 1),
      createAbility('adam-3', 'Survivor Tactics', 'Usa adaptabilidade de sobrevivente aumentando evasão em 20%.', 'Defense', 2),
      createAbility('adam-4', 'Adaptability', 'Ultimate: Adapta-se a qualquer situação aumentando todos os stats em 25%.', 'Support', 3),
    ],
    stats: createStats(3600, 1600, 17000, 95),
  },
  {
    id: 'swift',
    name: 'Swift',
    rarity: 'UR',
    type: 'Míssil',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/swift.png',
    description: 'Ultra-fast missile vehicle specializing in hit-and-run tactics.',
    abilities: [
      createAbility('swift-1', 'Hit and Run', 'Realiza ataque rápido e fuga. Dano aumentado com velocidade.', 'Damage', 1),
      createAbility('swift-2', 'Speed Boost', 'Passiva: Aumenta velocidade do esquadrão em 40%.', 'Support', 1),
      createAbility('swift-3', 'Ultra-fast Maneuvers', 'Executa manobras ultra-rápidas aumentando evasão em 30%.', 'Defense', 2),
      createAbility('swift-4', 'Speed Master', 'Ultimate: Domínio de velocidade aumentando SPD em 50%.', 'Support', 3),
    ],
    stats: createStats(3700, 1500, 16000, 130),
  },
  {
    id: 'fiona',
    name: 'Fiona',
    rarity: 'UR',
    type: 'Míssil',
    role: 'Dano',
    position: 'Back Row',
    tier: 'S+',
    image: '/heroes/fiona.png',
    description: 'S+-tier Missile Vehicle nuker. Devastating AoE physical damage dealer. HIGHEST DPS.',
    abilities: [
      createAbility('fiona-1', 'Double Trajectory', 'Dispara mísseis de trajetória dupla causando dano em área. Maior dano AoE.', 'Damage', 1),
      createAbility('fiona-2', 'Ballistic Boost', 'Passiva: Aumenta dano balístico em 40%. Efeito mais forte que outros.', 'Support', 1),
      createAbility('fiona-3', 'AoE Devastation', 'Cria devastação massiva em área afetando todos os inimigos.', 'Damage', 2),
      createAbility('fiona-4', 'Nuker Master', 'Ultimate: Expertise em AoE aumentando dano em 60%. Maior dano da classe.', 'Damage', 3),
    ],
    stats: createStats(4200, 1400, 15000, 90),
  },
  {
    id: 'venom',
    name: 'Venom',
    rarity: 'SSR',
    type: 'Míssil',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/venom.png',
    description: 'Poison-based missile with damage over time effects.',
    abilities: [
      createAbility('venom-1', 'Poison Strike', 'Ataque com veneno causando dano continuado. Envenena inimigos.', 'Damage', 1),
      createAbility('venom-2', 'Poison Cloud', 'Passiva: Cria nuvem de veneno reduzindo dano inimigo em 15%.', 'Control', 1),
      createAbility('venom-3', 'Toxic Damage', 'Causa dano tóxico continuamente em inimigos por 10 segundos.', 'Damage', 2),
      createAbility('venom-4', 'Poison Master', 'Ultimate: Domínio de veneno aumentando dano contínuo em 50%.', 'Damage', 3),
    ],
    stats: createStats(3200, 1500, 16000, 100),
  },
  {
    id: 'braz',
    name: 'Braz',
    rarity: 'SSR',
    type: 'Míssil',
    role: 'Dano',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/braz.png',
    description: 'Brawler-style missile with melee combat abilities.',
    abilities: [
      createAbility('braz-1', 'Brawler Strike', 'Ataque de lutador poderoso causando dano alto. Estilo corpo a corpo.', 'Damage', 1),
      createAbility('braz-2', 'Toughness', 'Passiva: Aumenta resistência e durabilidade em 20%.', 'Defense', 1),
      createAbility('braz-3', 'Brawler Tactics', 'Usa táticas de combate corpo a corpo aumentando dano em 25%.', 'Damage', 2),
      createAbility('braz-4', 'Brawler', 'Ultimate: Expertise em combate corpo a corpo aumentando dano em 40%.', 'Damage', 3),
    ],
    stats: createStats(3400, 1700, 18000, 85),
  },
  {
    id: 'kane',
    name: 'Kane',
    rarity: 'SR',
    type: 'Míssil',
    role: 'Dano',
    position: 'Back Row',
    tier: 'B',
    image: '/heroes/kane.png',
    description: 'Assassin-style missile with stealth and burst damage.',
    abilities: [
      createAbility('kane-1', 'Assassin Strike', 'Ataque rápido de assassino causando dano massivo. Crítico garantido.', 'Damage', 1),
      createAbility('kane-2', 'Shadow Cloak', 'Passiva: Envolve-se em sombras para furtividade reduzindo dano em 15%.', 'Defense', 1),
      createAbility('kane-3', 'Assassination', 'Realiza ataque de assassinato ignorando defesa parcialmente.', 'Damage', 2),
      createAbility('kane-4', 'Assassin', 'Ultimate: Expertise em assassinato aumentando dano crítico em 50%.', 'Damage', 3),
    ],
    stats: createStats(3100, 1400, 14000, 115),
  },
  {
    id: 'elsa',
    name: 'Elsa',
    rarity: 'SSR',
    type: 'Míssil',
    role: 'Defesa',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/elsa.png',
    description: 'Frost-based missile with crowd control abilities.',
    abilities: [
      createAbility('elsa-1', 'Frost Strike', 'Ataque com gelo causando dano de gelo. Congela inimigos.', 'Control', 1),
      createAbility('elsa-2', 'Freeze', 'Passiva: Congela inimigos reduzindo velocidade em 30%.', 'Control', 1),
      createAbility('elsa-3', 'Frost Aura', 'Cria aura de gelo protegendo aliados reduzindo dano em 20%.', 'Defense', 2),
      createAbility('elsa-4', 'Frost Master', 'Ultimate: Domínio de gelo congelando inimigos por 5 segundos.', 'Control', 3),
    ],
    stats: createStats(2800, 2000, 19000, 105),
  },
  {
    id: 'monica',
    name: 'Monica',
    rarity: 'SSR',
    type: 'Míssil',
    role: 'Suporte',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/monica.png',
    description: 'Medical support missile providing healing and buffs.',
    abilities: [
      createAbility('monica-1', 'Medical Support', 'Fornece suporte médico curando aliados. Restaura HP.', 'Support', 1),
      createAbility('monica-2', 'Healing Aura', 'Passiva: Cria aura de cura restaurando HP de aliados continuamente.', 'Support', 1),
      createAbility('monica-3', 'Support Boost', 'Aumenta efetividade de suporte em 30%.', 'Support', 2),
      createAbility('monica-4', 'Healer', 'Ultimate: Expertise em cura restaurando HP em 50% e removendo debuffs.', 'Support', 3),
    ],
    stats: createStats(2200, 1800, 17000, 95),
  },
  {
    id: 'cage',
    name: 'Cage',
    rarity: 'SSR',
    type: 'Míssil',
    role: 'Defesa',
    position: 'Back Row',
    tier: 'A',
    image: '/heroes/cage.png',
    description: 'Containment-based missile with crowd control.',
    abilities: [
      createAbility('cage-1', 'Cage Strike', 'Ataque que aprisiona inimigos. Imobiliza por 3 segundos.', 'Control', 1),
      createAbility('cage-2', 'Containment', 'Passiva: Contém movimentos de inimigos reduzindo velocidade em 25%.', 'Control', 1),
      createAbility('cage-3', 'Trap Setup', 'Configura armadilhas reduzindo dano recebido em 20%.', 'Defense', 2),
      createAbility('cage-4', 'Cage Master', 'Ultimate: Expertise em contenção aprisionando inimigos por 8 segundos.', 'Control', 3),
    ],
    stats: createStats(2600, 2400, 22000, 80),
  },
];

export const HERO_TYPES = {
  'Tanque': {
    label: '🛡️ Tanque',
    advantage: 'Resistência e Proteção',
  },
  'Aeronave': {
    label: '✈️ Aeronave',
    advantage: 'Velocidade e Mobilidade',
  },
  'Míssil': {
    label: '🚀 Míssil',
    advantage: 'Dano e Controle',
  },
};
